/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.teesa.cotizaciones.crud;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhonn
 */
public class VistaNuevaCotizacion extends javax.swing.JFrame {

    /**
     * Creates new form VistaNuevaCotizacion
     */
    private DefaultTableModel modeloTabla;
    
    public VistaNuevaCotizacion() {
        initComponents();
        configurarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_Cliente_Cotizacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Encargado_Cotizacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Correo_Cotizacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Cargo_Cotizacion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_descuento_cotizacion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_fecha_cotizacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_tecnico_cotizacion = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProductos);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Cliente"));

        jButton4.setText("Seleccionar Cliente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente");

        txt_Cliente_Cotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Cliente_CotizacionActionPerformed(evt);
            }
        });

        jLabel2.setText("Encargado");

        jLabel3.setText("Correo");

        jLabel4.setText("Cargo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_Cliente_Cotizacion)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txt_Encargado_Cotizacion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txt_Correo_Cotizacion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txt_Cargo_Cotizacion)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Cliente_Cotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Encargado_Cotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Correo_Cotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Cargo_Cotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Otros datos"));

        jLabel6.setText("Descuento");

        jLabel7.setText("Fecha");

        jLabel8.setText("Tecnico");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txt_descuento_cotizacion, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txt_fecha_cotizacion))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txt_tecnico_cotizacion)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_descuento_cotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fecha_cotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tecnico_cotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jButton2.setText("Finalizar Cotizacion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar producto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(580, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //DefaultTableModel modelo = (DefaultTableModel) jTableProductos.getModel();
        //modelo.addRow(new Object[]{"Producto " + (modelo.getRowCount() + 1), Math.random() * 100, 1});
        
        
        //VistaDummy objetoVistaDummy = new VistaDummy(this); //Le paso la referencia de esta vista en la que estoy
        //objetoVistaDummy.setVisible(true); // Abro otra ventana donde se agregara el producto
        
        VistaSeleccionarProducto objetoSeleccionarProducto = new VistaSeleccionarProducto(this);
        objetoSeleccionarProducto.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    //Para mostrar todos los datos de la tabla , aqui se pasaria la info a un pdf
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
             DefaultTableModel modelo = (DefaultTableModel) jTableProductos.getModel();
             // Crear una lista de ProductosCotizacion
            List<ProductosCotizacion> productos = new ArrayList<>();
            Float totalParcial=(float)0.0;
            Float ofertaTotal;
        for (int i = 0; i < modelo.getRowCount(); i++) {
            String nombreProducto = (String) modelo.getValueAt(i, 0);
            String marcaProducto = (String) modelo.getValueAt(i, 1);
            String descripProducto = (String) modelo.getValueAt(i, 2);
            double precioUnidad = (double) modelo.getValueAt(i, 3);
            int cantidad = Integer.parseInt (modelo.getValueAt(i, 4).toString());
            
            ProductosCotizacion nuevoProducto = new ProductosCotizacion();
            nuevoProducto.setItem(i+1);
            nuevoProducto.setNombre(nombreProducto);
            nuevoProducto.setMarca(marcaProducto);
            nuevoProducto.setDescripcion(descripProducto);
            nuevoProducto.setCantidad(cantidad);
            nuevoProducto.setValorUnidad((float)precioUnidad);
            nuevoProducto.setValorTotal( (float)(cantidad*precioUnidad));
            
            productos.add(nuevoProducto);
            totalParcial += (float)(cantidad*precioUnidad);
            // System.out.println("Producto: " + producto + ", Precio: " + precio + ", Cantidad: " + cantidad);
            // Pruebas ....
            
             // Crear objetos de ProductosCotizacion
            //ProductosCotizacion producto1 = new ProductosCotizacion();
            //producto1.setItem(1);
            //producto1.setNombre("Producto A");
            //producto1.setMarca("Marca A");
            //producto1.setDescripcion("Descripción A");
            //producto1.setCantidad(10);
            //producto1.setValorUnidad(50.0f);
            //producto1.setValorTotal(500.0f);

            //ProductosCotizacion producto2 = new ProductosCotizacion();
            //producto2.setItem(2);
            //producto2.setNombre("Producto B");
            //producto2.setMarca("Marca B");
            //producto2.setDescripcion("Descripción B");
            //producto2.setCantidad(5);
            //producto2.setValorUnidad(30.0f);
            //producto2.setValorTotal(150.0f);
            
            //productos.add(producto1);
            //productos.add(producto2);
            
        }
        ofertaTotal= totalParcial;
         
        if (txt_descuento_cotizacion.getText() != null && !txt_descuento_cotizacion.getText().isEmpty()) {
            try {
                   
                    System.out.println("oferta total:"+ofertaTotal);
                    float descuento = Float.parseFloat(txt_descuento_cotizacion.getText());
                    ofertaTotal = ofertaTotal - ofertaTotal * (descuento / 100);
                     System.out.println("oferta total:"+ofertaTotal);
                } catch (NumberFormatException e) {
                // Manejar errores si el texto no es un número válido
                System.out.println("Error: El valor de descuento no es un número válido.");
                }
         }
        
        // Aplicar el IVA del 19%
        ofertaTotal = ofertaTotal * (float)1.19;
         System.out.println("oferta total:"+ofertaTotal);

            ObjetoCotizacion nuevaCotizacion= new ObjetoCotizacion(txt_Cliente_Cotizacion.getText(),txt_fecha_cotizacion.getText() ,txt_Encargado_Cotizacion.getText(),"",Float.parseFloat(txt_descuento_cotizacion.getText()),totalParcial,ofertaTotal,productos);
            //ObjetoCotizacion nuevaCotizacion= new ObjetoCotizacion("Deliasados","12-01-2024","Juanita Tocamela","Nota ejemplo",1,100,120,productos);
            generarPDF(nuevaCotizacion);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Error: "+e.toString());
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed
    //Eliminar producto , fila seleccionada
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         int filaSeleccionada = jTableProductos.getSelectedRow();

        if (filaSeleccionada >= 0) {
            // Eliminar la fila seleccionada del modelo
            modeloTabla.removeRow(filaSeleccionada);
            JOptionPane.showMessageDialog(this, "Fila eliminada con éxito.");
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila para eliminar.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        VistaSeleccionarCliente objetoSeleccionarCliente = new VistaSeleccionarCliente(this);
        objetoSeleccionarCliente.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_Cliente_CotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Cliente_CotizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Cliente_CotizacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaNuevaCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaNuevaCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaNuevaCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaNuevaCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaNuevaCotizacion().setVisible(true);
            }
        });
    }
    
    //Configuro la tabla directamente con los campos que necesite
     private void configurarTabla() {
        modeloTabla = new DefaultTableModel(
                new Object[][]{}, 
                new String[]{"Producto","Marca","Descripción", "Precio", "Cantidad"}
        ) {
            //Defino la celda que sera editable, en este caso la catidad
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 4; // Solo la columna "Cantidad" es editable
            }
        };

        jTableProductos.setModel(modeloTabla); // Asignar modelo a la tabla
    }
     
     public void agregarProducto(String producto,String marca,String descripcion, double precio, int cantidad) {
        modeloTabla.addRow(new Object[]{producto,marca,descripcion, precio, cantidad});
    }
     
    public void agregarCliente(String cliente, String encargado, String correo, String cargo) {
       txt_Cliente_Cotizacion.setText(cliente);
       txt_Encargado_Cotizacion.setText(encargado);
       txt_Correo_Cotizacion.setText(correo);
       txt_Cargo_Cotizacion.setText(cargo);
    }
     
    private void generarPDF(ObjetoCotizacion cotizacion ){
        
          System.out.println("Cliente: " + cotizacion.getNombreCliente());
          System.out.println("Encargado: " + cotizacion.getEncargado());
          System.out.println("---------------------------");
          System.out.println("Descuento: " + cotizacion.getDescuento());
          System.out.println("---------------------------");
          System.out.println("Total Parcial: " + cotizacion.getTotalParcial());
          System.out.println("---------------------------");
          System.out.println("Oferta Total: " + cotizacion.getOfertaTotal());
          System.out.println("---------------------------");
          System.out.println("Productos: ");
           System.out.println("---------------------------");
          
           for (ProductosCotizacion producto : cotizacion.getProductos()) {
            System.out.println("Item: " + producto.getItem());
            System.out.println("Nombre: " + producto.getNombre());
            System.out.println("Marca: " + producto.getMarca());
            System.out.println("Descripción: " + producto.getDescripcion());
            System.out.println("Cantidad: " + producto.getCantidad());
            System.out.println("Valor Unidad: " + producto.getValorUnidad());
            System.out.println("Valor Total: " + producto.getValorTotal());
            System.out.println("---------------------------");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField txt_Cargo_Cotizacion;
    private javax.swing.JTextField txt_Cliente_Cotizacion;
    private javax.swing.JTextField txt_Correo_Cotizacion;
    private javax.swing.JTextField txt_Encargado_Cotizacion;
    private javax.swing.JTextField txt_descuento_cotizacion;
    private javax.swing.JTextField txt_fecha_cotizacion;
    private javax.swing.JTextField txt_tecnico_cotizacion;
    // End of variables declaration//GEN-END:variables
}
